-- 코드를 입력하세요
SELECT TITLE,A.BOARD_ID,A.REPLY_ID,A.WRITER_ID,A.CONTENTS,DATE_FORMAT(A.CREATED_DATE,'%Y-%m-%d') as CREATED_DATE 
from  USED_GOODS_REPLY as A JOIN USED_GOODS_BOARD as B
ON A.BOARD_ID = B.BOARD_ID 
WHERE DATE_FORMAT(B.CREATED_DATE,'%Y-%m') = '2022-10' 
ORDER BY A.CREATED_DATE,TITLE ASC